const trade = [
  { tradeName: "gift card trade", tradeAmount: "80" },
  { tradeName: "crypto trade", tradeAmount: "90" },
  { tradeName: "btc trade", tradeAmount: "$ 3,128.30" },
  { tradeName: "usdt trade", tradeAmount: "$ 1,128.80" },
  { tradeName: "crypto sent", tradeAmount: "$ 328.80" },
];

const withdraw = [
  { withdrawName: "withdrawals", withdrawAmount: "77" },
  { withdrawName: "ngn withdrawals", withdrawAmount: "77" },
  { withdrawName: "usd withdrawals", withdrawAmount: "77" },
  { withdrawName: "ghs withdrawals", withdrawAmount: "77" },
  { withdrawName: "kyn withdrawals", withdrawAmount: "77" },
];

const total = [
  { totalName: "total crypto balance", totalAmount: "$ 32,100" },
  { totalName: "total usd balance", totalAmount: "$ 32,100" },
  { totalName: "total ngn balance", totalAmount: "$ 32,100" },
  { totalName: "total virtual card balance", totalAmount: "$ 32,100" },
  { totalName: "fx conversion", totalAmount: "67" },
  { totalName: "total naira withdraw", totalAmount: "N 32,100" },
  { totalName: "total usd withdraw", totalAmount: "$ 32,100" },
  { totalName: "giftcard traded volume", totalAmount: "$ 32,100" },
  { totalName: "daily new user", totalAmount: "67" },
  { totalName: "total user", totalAmount: "167" },
  { totalName: "andriod download", totalAmount: "77" },
  { totalName: "ios download", totalAmount: "97" },
  { totalName: "vitual card created", totalAmount: "77" },
  { totalName: "daily virtual card transaction", totalAmount: "77" },
];

//gift card data
const giftCard = [
  {
    email: "xvalz@gmail.com",
    giftCard: "steam",
    country: "USA",
    cardType: "ecode",
    amount: "100",
    payout: "66,000",
    transDate: "22/3/2023",
    transTime: "8:30",
  },
  {
    email: "xvalz@gmail.com",
    giftCard: "steam",
    country: "USA",
    cardType: "ecode",
    amount: "200",
    payout: "66,000",
    transDate: "22/3/2023",
    transTime: "8:30",
  },
  {
    email: "xvalz@gmail.com",
    giftCard: "steam",
    country: "USA",
    cardType: "ecode",
    amount: "300",
    payout: "66,000",
    transDate: "22/3/2023",
    transTime: "8:30",
  },
  {
    email: "xvalz@gmail.com",
    giftCard: "steam",
    country: "USA",
    cardType: "ecode",
    amount: "400",
    payout: "66,000",
    transDate: "22/3/2023",
    transTime: "8:30",
  },
  {
    email: "xvalz@gmail.com",
    giftCard: "steam",
    country: "USA",
    cardType: "ecode",
    amount: "500",
    payout: "66,000",
    transDate: "22/3/2023",
    transTime: "8:30",
  },
  {
    email: "xvalz@gmail.com",
    giftCard: "steam",
    country: "USA",
    cardType: "ecode",
    amount: "600",
    payout: "66,000",
    transDate: "22/3/2023",
    transTime: "8:30",
  },
  {
    email: "xvalz@gmail.com",
    giftCard: "steam",
    country: "USA",
    cardType: "ecode",
    amount: "700",
    payout: "66,000",
    transDate: "22/3/2023",
    transTime: "8:30",
  },
  {
    email: "xvalz@gmail.com",
    giftCard: "steam",
    country: "USA",
    cardType: "ecode",
    amount: "800",
    payout: "66,000",
    transDate: "22/3/2023",
    transTime: "8:30",
  },
  {
    email: "xvalz@gmail.com",
    giftCard: "steam",
    country: "USA",
    cardType: "ecode",
    amount: "900",
    payout: "66,000",
    transDate: "22/3/2023",
    transTime: "8:30",
  },
  {
    email: "xvalz@gmail.com",
    giftCard: "steam",
    country: "USA",
    cardType: "ecode",
    amount: "200",
    payout: "66,000",
    transDate: "22/3/2023",
    transTime: "8:30",
  },
];

export { trade, withdraw, total, giftCard };
