const trade = [
  { tradeName: "gift card trade", tradeAmount: 80 },
  { tradeName: "crypto trade", tradeAmount: 90 },
  { tradeName: "btc trade", tradeAmount: 3128.30 },
  { tradeName: "usdt trade", tradeAmount: 1128.80 },
  { tradeName: "crypto sent", tradeAmount: 328.80 },
];

const withdraw = [
  { withdrawName: "withdrawals", withdrawAmount: 77 },
  { withdrawName: "ngn withdrawals", withdrawAmount: 77 },
  { withdrawName: "usd withdrawals", withdrawAmount: 77 },
  { withdrawName: "ghs withdrawals", withdrawAmount: 77 },
  { withdrawName: "kyn withdrawals", withdrawAmount: 77 },
];

const total = [
  { totalName: "total crypto balance", totalAmount: 32100 },
  { totalName: "total usd balance", totalAmount: 32100 },
  { totalName: "total ngn balance", totalAmount: 32100 },
  { totalName: "total virtual card balance", totalAmount: 32100 },
  { totalName: "total naira withdraw", totalAmount: 32100 },
  { totalName: "total usd withdraw", totalAmount: 32100 },
  { totalName: "giftcard traded volume", totalAmount: 32100 },
  // { totalName: "vitual card created", totalAmount: "77" },
  // { totalName: "daily virtual card transaction", totalAmount: "77" },
];

const cards = [
  { totalName: "fx conversion", totalAmount: 67 },
  { totalName: "daily new user", totalAmount: 67 },
  { totalName: "total user", totalAmount: 167 },
  { totalName: "andriod download", totalAmount: 77 },
  { totalName: "ios download", totalAmount: 97 },
  { totalName: "vitual card created", totalAmount: 77 },
  { totalName: "daily virtual card transaction", totalAmount: 77 },
];

//gift card data
const giftCard = [
  {
    email: "xvalz@gmail.com",
    giftCard: "steam",
    country: "USA",
    cardType: "ecode",
    amount: "100",
    payout: "66,000",
    name: "John Doe",
    transDate: "22/3/2023",
    transTime: "8:30",
  },
  {
    email: "xvalz@gmail.com",
    giftCard: "steam",
    country: "USA",
    cardType: "ecode",
    amount: "100",
    payout: "66,000",
    name: "John Doe",
    transDate: "22/3/2023",
    transTime: "8:30",
  },
  {
    email: "xvalz@gmail.com",
    giftCard: "steam",
    country: "USA",
    cardType: "ecode",
    amount: "100",
    payout: "66,000",
    name: "John Doe",
    transDate: "22/3/2023",
    transTime: "8:30",
  },
  {
    email: "xvalz@gmail.com",
    giftCard: "steam",
    country: "USA",
    cardType: "ecode",
    amount: "100",
    payout: "66,000",
    name: "John Doe",
    transDate: "22/3/2023",
    transTime: "8:30",
  },
  {
    email: "xvalz@gmail.com",
    giftCard: "steam",
    country: "USA",
    cardType: "ecode",
    amount: "100",
    payout: "66,000",
    name: "John Doe",
    transDate: "22/3/2023",
    transTime: "8:30",
  },
  {
    email: "xvalz@gmail.com",
    giftCard: "steam",
    country: "USA",
    cardType: "ecode",
    amount: "100",
    payout: "66,000",
    name: "John Doe",
    transDate: "22/3/2023",
    transTime: "8:30",
  },
  {
    email: "xvalz@gmail.com",
    giftCard: "steam",
    country: "USA",
    cardType: "ecode",
    amount: "100",
    payout: "66,000",
    name: "John Doe",
    transDate: "22/3/2023",
    transTime: "8:30",
  },
  {
    email: "xvalz@gmail.com",
    giftCard: "steam",
    country: "USA",
    cardType: "ecode",
    amount: "100",
    payout: "66,000",
    name: "John Doe",
    transDate: "22/3/2023",
    transTime: "8:30",
  },
  {
    email: "xvalz@gmail.com",
    giftCard: "steam",
    country: "USA",
    cardType: "ecode",
    amount: "100",
    payout: "66,000",
    name: "John Doe",
    transDate: "22/3/2023",
    transTime: "8:30",
  },
  {
    email: "xvalz@gmail.com",
    giftCard: "steam",
    country: "USA",
    cardType: "ecode",
    amount: "100",
    payout: "66,000",
    name: "John Doe",
    transDate: "22/3/2023",
    transTime: "8:30",
  },
  {
    email: "xvalz@gmail.com",
    giftCard: "steam",
    country: "USA",
    cardType: "ecode",
    amount: "100",
    payout: "66,000",
    name: "John Doe",
    transDate: "22/3/2023",
    transTime: "8:30",
  },
  {
    email: "xvalz@gmail.com",
    giftCard: "steam",
    country: "USA",
    cardType: "ecode",
    amount: "100",
    payout: "66,000",
    name: "John Doe",
    transDate: "22/3/2023",
    transTime: "8:30",
  },
  {
    email: "xvalz@gmail.com",
    giftCard: "steam",
    country: "USA",
    cardType: "ecode",
    amount: "100",
    payout: "66,000",
    name: "John Doe",
    transDate: "22/3/2023",
    transTime: "8:30",
  },
  {
    email: "xvalz@gmail.com",
    giftCard: "steam",
    country: "USA",
    cardType: "ecode",
    amount: "100",
    payout: "66,000",
    name: "John Doe",
    transDate: "22/3/2023",
    transTime: "8:30",
  },
  {
    email: "xvalz@gmail.com",
    giftCard: "steam",
    country: "USA",
    cardType: "ecode",
    amount: "100",
    payout: "66,000",
    name: "John Doe",
    transDate: "22/3/2023",
    transTime: "8:30",
  },
  {
    email: "xvalz@gmail.com",
    giftCard: "steam",
    country: "USA",
    cardType: "ecode",
    amount: "100",
    payout: "66,000",
    name: "John Doe",
    transDate: "22/3/2023",
    transTime: "8:30",
  },
  {
    email: "xvalz@gmail.com",
    giftCard: "steam",
    country: "USA",
    cardType: "ecode",
    amount: "100",
    payout: "66,000",
    name: "John Doe",
    transDate: "22/3/2023",
    transTime: "8:30",
  },
  {
    email: "xvalz@gmail.com",
    giftCard: "steam",
    country: "USA",
    cardType: "ecode",
    amount: "100",
    payout: "66,000",
    name: "John Doe",
    transDate: "22/3/2023",
    transTime: "8:30",
  },
  {
    email: "xvalz@gmail.com",
    giftCard: "steam",
    country: "USA",
    cardType: "ecode",
    amount: "100",
    payout: "66,000",
    name: "John Doe",
    transDate: "22/3/2023",
    transTime: "8:30",
  },
];

const country = [
  
]

export { trade, withdraw, total, giftCard, cards };
