const menu = [
  { name: "Dashboard", link: "/dashboard", count: "" },
  { name: "Chat", link: "/chat", count: "" },
  { name: "admin control", link: "/admin-control", count: "" },
  { name: "buy gift card", link: "/buy-gift-card", count: "4" },
  { name: "sell gift card", link: "/sell-gift-card", count: "" },
  { name: "P2P tranx", link: "/p2p-tranx", count: "3" },
  { name: "virtual card", link: "/virtual-card", count: "7" },
  { name: "crypto tranx", link: "/crypto-tranx", count: "3" },
  { name: "pending crypto tranx", link: "/pending-crypto-tranx", count: "3" },
  { name: "users", link: "/users", count: "" },
  { name: "news", link: "/news", count: "" },
  { name: "FAQ", link: "/faq", count: "" },
  { name: "USD withdrawal", link: "/usd-withdraw", count: "" },
  { name: "NGN withdrawal", link: "/ngn-withdraw", count: "5" },
  { name: "GHS withdrawal", link: "/ghs-withdraw", count: "" },
  { name: "FX Rate", link: "/fx-Rate", count: "" },
  { name: "Crypto Rate", link: "/crypto-Rate", count: "" },
  {
    name: "Gift Card Rate",
    subMenu: [
      {
        name: "Upload",
        link: "/giftcard/upload",
      },
      {
        name: "Add",
        link: "/giftcard/add",
      },
    ],
  },
  { name: "NGN Deposit", link: "/ngn-deposit", count: "" },
  { name: "USD Deposit", link: "/usd-deposit", count: "" },
  { name: "push notification", link: "/push-notice", count: "" },
  { name: "export data", link: "/export-data", count: "" },
  { name: "ads campaign", link: "/ads-campaign", count: "" },
  { name: "send email BC", link: "/send-email", count: "" },
  { name: "Tele Sales", link: "/telesales", count: "" },
  { name: "Ticketing", link: "/ticketing/all activies", count: "" },
  { name: "Bulk Sms", link: "/bulk-sms", count: "" },
  { name: "Paybills", link: "/paybills", count: "" },
  { name: "KYC 1 & 2", link: "/kyc-1&2", count: "" },
  { name: "KYC 3", link: "/kyc-3", count: "" },
  // { name: "KYC 4", link: "/kyc-4", count: "" },
];

export default menu;
