const menu = [
  { name: "dashboard", link: "/dashboard", count: "" },
  { name: "admin control", link: "/admin-control", count: "5" },
  { name: "gift card tranx", link: "/gift-card-tranx", count: "4" },
  { name: "P2P tranx", link: "/p2p-tranx", count: "3" },
  { name: "virtual card", link: "/virtual-card", count: "7" },
  { name: "crypto tranx", link: "/crypto-tranx", count: "3" },
  { name: "users", link: "/users", count: "" },
  { name: "news", link: "/news", countt: "" },
  { name: "FAQ", link: "/faq", count: "" },
  { name: "USD withdrawal", link: "/usd-withdraw", count: "" },
  { name: "NGN withdrawal", link: "/ngn-withdraw", count: "" },
  { name: "GHS withdrawal", link: "/ghs-withdraw", count: "" },
  { name: "FX Rate", link: "/fx-Rate", count: "" },
  { name: "Crypto Rate", link: "/crypto-Rate", count: "" },
  { name: "Gift Card Rate", link: "/gift-card-Rate", count: "" },
  { name: "NGN Deposit", link: "/ngn-deposit", count: "" },
  { name: "USD Deposit", link: "/usd-deposit", count: "" },
  { name: "NGN transfer", link: "/ngn-transfer", count: "" },
  { name: "USD transfer", link: "/usd-transfer", count: "" },
  { name: "push notification", link: "/push-notice", count: "" },
  { name: "export data", link: "/export-data", count: "" },
  { name: "ads campaign", link: "/ads-campaign", count: "" },
  { name: "send email BC", link: "/send-email", count: "" },
  { name: "KYC 1 & 2", link: "/kyc-1&2", count: "" },
  { name: "KYC 3", link: "/kyc-3", count: "" },
  { name: "KYC 4", link: "/kyc-4", count: "" },
];

export default menu;
